export default {
  common: { login: 'लॉग इन', logout: 'लॉग आउट', save: 'सहेजें', cancel: 'रद्द करें', submit: 'जमा करें', search: 'खोजें', loading: 'लोड हो रहा है...', error: 'त्रुटि', success: 'सफल', back: 'वापस', home: 'होम', profile: 'प्रोफ़ाइल', email: 'ईमेल', password: 'पासवर्ड', name: 'नाम', phone: 'फ़ोन', actions: 'कार्रवाई', view: 'देखें', edit: 'संपादित करें', delete: 'हटाएं', confirm: 'पुष्टि करें', close: 'बंद करें', yes: 'हाँ', no: 'नहीं', welcome: 'स्वागत है', location: 'स्थान', latitude: 'अक्षांश', longitude: 'देशांतर', yearsExp: 'वर्ष का अनुभव', kmAway: 'किमी दूर', activeJobs: 'सक्रिय कार्य', noData: 'कोई डेटा उपलब्ध नहीं', required: 'आवश्यक' },
  navigation: { dashboard: 'डैशबोर्ड', workers: 'कर्मचारी', bookings: 'बुकिंग', profile: 'प्रोफ़ाइल', findService: 'सेवा खोजें', myJobs: 'मेरे कार्य', adminPanel: 'प्रशासन पैनल', home: 'होम', verification: 'सत्यापन', workloadMonitor: 'कार्यभार मॉनिटर' },
  landing: { title: 'गिगसेतु', tagline: 'स्थानीय काम। निष्पक्ष वितरण।', heroText: 'विश्वसनीय स्थानीय पेशेवरों से जुड़ें और हर कर्मचारी के लिए उचित अवसर बनाएं।', heroSubtext: 'भारत का पहला सहकारी स्वामित्व वाला हाइपरलोकल गिग प्लेटफ़ॉर्म जो उचित कार्य वितरण सुनिश्चित करता है।', benefit1Title: 'सत्यापित कर्मचारी', benefit1Desc: 'हर कर्मचारी को काम मिलने से पहले सहकारी द्वारा सत्यापित किया जाता है।', benefit2Title: 'निष्पक्ष कार्य आवंटन', benefit2Desc: 'हमारा निष्पक्षता एल्गोरिदम सभी कर्मचारियों के बीच काम को समान रूप से वितरित करता है।', benefit3Title: 'हाइपरलोकल सेवाएं', benefit3Desc: 'अपने पड़ोस में विश्वसनीय पेशेवर खोजें।', findService: 'सेवा खोजें', joinAsWorker: 'कर्मचारी बनें', builtForEveryone: 'सबके लिए बनाया गया', availableLanguages: 'अंग्रेजी, हिंदी और कन्नड में उपलब्ध।', howItWorks: 'यह कैसे काम करता है', step1: 'सेवा खोजें', step1Desc: 'आपको जिस प्रकार की सेवा चाहिए उसे चुनें और अपनी आवश्यकता बताएं।', step2: 'निष्पक्ष सिफारिशें पाएं', step2Desc: 'हमारा AI-संचालित निष्पक्षता एल्गोरिदम कौशल, दूरी, उपलब्धता और कार्यभार संतुलन के आधार पर कर्मचारियों की सिफारिश करता है।', step3: 'बुक करें और ट्रैक करें', step3Desc: 'कर्मचारी बुक करें और अपनी सेवा को रियल-टाइम में ट्रैक करें।', cooperativeOwned: 'सहकारी स्वामित्व', cooperativeDesc: 'स्थानीय समुदायों द्वारा और उनके लिए बनाया गया।', sihProject: 'स्मार्ट इंडिया हैकाथॉन 2026 प्रोजेक्ट' },
  auth: { loginTitle: 'वापस स्वागत है', registerTitle: 'खाता बनाएं', selectRole: 'अपनी भूमिका चुनें', customerLogin: 'ग्राहक लॉगिन', workerLogin: 'कर्मचारी लॉगिन', adminLogin: 'प्रशासक लॉगिन', customerRole: 'ग्राहक', workerRole: 'गिग वर्कर', adminRole: 'सहकारी नेता', noAccount: 'खाता नहीं है?', haveAccount: 'पहले से खाता है?', registerHere: 'यहां रजिस्टर करें', loginHere: 'यहां लॉगिन करें', registerAs: 'के रूप में रजिस्टर करें', customerDesc: 'अपनी जरूरतों के लिए विश्वसनीय स्थानीय पेशेवर खोजें।', workerDesc: 'सहकारी में शामिल हों और उचित काम के अवसर पाएं।', adminDesc: 'कर्मचारियों का प्रबंधन करें, प्रोफाइल सत्यापित करें और निष्पक्षता की निगरानी करें।' },
  customer: { findService: 'सेवा खोजें', serviceRequired: 'आवश्यक सेवा', description: 'अपनी जरूरत बताएं', descriptionPlaceholder: 'जैसे, सीलिंग फैन की मरम्मत में मदद चाहिए', findWorkers: 'कर्मचारी खोजें', requestService: 'सेवा का अनुरोध करें', myBookings: 'मेरी बुकिंग', currentBooking: 'वर्तमान बुकिंग', bookingHistory: 'बुकिंग इतिहास', recommended: 'अनुशंसित कर्मचारी', bestFairMatch: 'सर्वश्रेष्ठ निष्पक्ष मिलान', whyThisWorker: 'यह कर्मचारी क्यों?', skillMatchReason: 'आपकी आवश्यकताओं के लिए मजबूत कौशल मिलान', distanceReason: 'आपके स्थान के करीब', availabilityReason: 'वर्तमान में काम के लिए उपलब्ध', workloadReason: 'कम वर्तमान कार्यभार - निष्पक्ष वितरण', ratingReason: 'ग्राहकों द्वारा उच्च रेटिंग', noWorkers: 'इस सेवा के लिए कोई कर्मचारी नहीं मिला। कोई अलग सेवा या स्थान आज़माएं।', useDefaultLocation: 'डिफ़ॉल्ट स्थान का उपयोग करें (बैंगलोर)', enterCoordinates: 'निर्देशांक दर्ज करें', searching: 'सर्वश्रेष्ठ निष्पक्ष मिलान खोजा जा रहा है...' , emergency: 'आपातकालीन सेवा', emergencyHelp: 'पास के उपलब्ध कर्मचारियों को प्राथमिकता दें', schedule: 'समय निर्धारित करें (वैकल्पिक)', useCurrentLocation: 'वर्तमान स्थान का उपयोग करें', locationDenied: 'स्थान की अनुमति नहीं मिली', locationUnsupported: 'जियोलोकेशन समर्थित नहीं है', searchFailed: 'खोज विफल हुई', bookingFailed: 'बुकिंग बनाना संभव नहीं हुआ', matches: 'मिलान'},
  worker: { workerPortal: 'कर्मचारी पोर्टल', availability: 'उपलब्धता', myJobs: 'मेरे कार्य', verified: 'सत्यापित', pending: 'सत्यापन लंबित', rejected: 'अस्वीकृत', verificationStatus: 'सत्यापन स्थिति', activeJobs: 'सक्रिय कार्य', completedJobs: 'पूर्ण कार्य', acceptJob: '✓ कार्य स्वीकार करें', rejectJob: '✗ कार्य अस्वीकार करें', startJob: '▶ कार्य शुरू करें', completeJob: '✓ कार्य पूरा करें', currentWorkload: 'वर्तमान कार्यभार', rating: 'रेटिंग', experience: 'अनुभव', skills: 'कौशल', updateProfile: 'प्रोफ़ाइल अपडेट करें', setAvailability: 'उपलब्धता सेट करें', available: 'उपलब्ध', partiallyAvailable: 'आंशिक रूप से उपलब्ध', unavailable: 'अनुपलब्ध', service: 'सेवा', pendingMessage: 'आपकी प्रोफ़ाइल सहकारी नेता द्वारा सत्यापन के लिए लंबित है। सत्यापित होने के बाद आप कार्य प्राप्त कर सकेंगे।', noJobs: 'अभी कोई कार्य नहीं है। नए अनुरोध यहां दिखाई देंगे।' },
  admin: { cooperativeDashboard: 'सहकारी डैशबोर्ड', totalWorkers: 'कुल कर्मचारी', verifiedWorkers: 'सत्यापित कर्मचारी', pendingWorkers: 'लंबित कर्मचारी', customers: 'ग्राहक', totalBookings: 'कुल बुकिंग', completedJobs: 'पूर्ण कार्य', activeJobs: 'सक्रिय कार्य', cancelledJobs: 'रद्द कार्य', workerVerification: 'कर्मचारी सत्यापन', verifyWorker: 'सत्यापित करें', rejectWorker: 'अस्वीकार करें', viewProfile: 'प्रोफ़ाइल देखें', workloadDistribution: 'कार्यभार वितरण', fairnessMonitor: 'निष्पक्षता मॉनिटर', allWorkers: 'सभी कर्मचारी', pendingOnly: 'केवल लंबित', verifiedOnly: 'केवल सत्यापित', recentBookings: 'हालिया बुकिंग', workerName: 'कर्मचारी का नाम', serviceType: 'सेवा प्रकार', experienceYears: 'अनुभव', status: 'स्थिति', federationAdministration: 'महासंघ एवं प्रशासन', cooperativeGovernance: 'सहकारी शासन', federationWorkers: 'महासंघ के कर्मचारी', admittedWorkers: 'स्वीकृत कर्मचारी', pendingAdmissions: 'लंबित प्रवेश', federationCustomers: 'महासंघ के ग्राहक', welfareEligible: 'कल्याण के पात्र', admissionGovernance: 'कर्मचारी प्रवेश एवं शासन', serviceCoverage: 'सेवा कवरेज' },
  services: { electrician: 'इलेक्ट्रीशियन', plumber: 'प्लंबर', carpenter: 'बढ़ई', cleaner: 'सफाईकर्मी', painter: 'पेंटर', gardener: 'माली', applianceRepair: 'उपकरण मरम्मत', delivery: 'डिलीवरी', farmWorker: 'कृषि कर्मचारी', otherServices: 'अन्य सामुदायिक सेवाएं' },
  fairness: { fairnessScore: 'निष्पक्षता स्कोर', aiMatchScore: 'AI मिलान स्कोर', skillMatch: 'कौशल मिलान', distance: 'दूरी', availability: 'उपलब्धता', workloadBalance: 'कार्यभार संतुलन', rating: 'रेटिंग', overallScore: 'समग्र स्कोर', combinedScore: 'संयुक्त स्कोर', scoreBreakdown: 'स्कोर विवरण' },
  booking: { requested: 'अनुरोधित', matched: 'मिलान किया गया', accepted: 'स्वीकृत', inProgress: 'कार्य प्रगति पर है', completed: 'पूरा हुआ', cancelled: 'रद्द किया गया', newRequest: 'नया अनुरोध', serviceRequest: 'सेवा अनुरोध', bookingDetails: 'बुकिंग विवरण', cancelBooking: 'बुकिंग रद्द करें', bookingCreated: 'बुकिंग सफलतापूर्वक बनाई गई!', noBookings: 'अभी तक कोई बुकिंग नहीं।' , customer: 'ग्राहक', worker: 'कर्मचारी', scheduledFor: 'निर्धारित समय'},
  notifications: { bookingAccepted: 'आपकी बुकिंग स्वीकार कर ली गई है!', bookingStarted: 'आपकी सेवा अब प्रगति पर है!', bookingCompleted: 'आपकी सेवा पूरी हो गई है!', newBooking: 'नया सेवा अनुरोध प्राप्त हुआ!', newBookingRequest: 'नया सेवा अनुरोध प्राप्त हुआ!', bookingCancelled: 'एक बुकिंग रद्द कर दी गई है।', workerVerified: 'आपकी प्रोफ़ाइल सत्यापित कर दी गई है!', paymentReceived: 'आपकी पूर्ण सेवा का भुगतान प्राप्त हो गया है!' },
  welfare: { title: 'कर्मचारी कल्याण', insurance: 'बीमा', fund: 'कल्याण निधि', safety: 'सुरक्षा प्रशिक्षण', certifications: 'प्रमाणपत्र', none: 'कोई प्रमाणपत्र दर्ज नहीं है' },
  payment: { title: 'डिजिटल भुगतान', amount: 'सेवा राशि (₹)', payNow: 'अभी भुगतान करें', paid: 'भुगतान पूरा हुआ', success: 'डेमो भुगतान सफल रहा', failed: 'भुगतान विफल', validAmount: 'मान्य राशि दर्ज करें' },
  rating: { title: 'इस सेवा को रेट करें', feedback: 'अपने अनुभव के बारे में बताएं (वैकल्पिक)', submit: 'रेटिंग भेजें', thanks: 'आपकी प्रतिक्रिया के लिए धन्यवाद!', failed: 'रेटिंग भेजना संभव नहीं हुआ' },
  invoice: { view: 'चालान देखें', failed: 'चालान बनाना संभव नहीं हुआ' },
  forecast: { title: 'AI मांग पूर्वानुमान', synthetic: 'प्रोटोटाइप पूर्वानुमान सिंथेटिक डेमो डेटा पर आधारित है। उत्पादन के लिए वास्तविक बुकिंग डेटा का उपयोग करें।' }
};
