export default {
  common: { login: 'ಲಾಗಿನ್', logout: 'ಲಾಗ್ ಔಟ್', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', submit: 'ಸಲ್ಲಿಸಿ', search: 'ಹುಡುಕಿ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', error: 'ದೋಷ', success: 'ಯಶಸ್ವಿ', back: 'ಹಿಂದೆ', home: 'ಮುಖಪುಟ', profile: 'ಪ್ರೊಫೈಲ್', email: 'ಇಮೇಲ್', password: 'ಪಾಸ್ವರ್ಡ್', name: 'ಹೆಸರು', phone: 'ಫೋನ್', actions: 'ಕ್ರಿಯೆಗಳು', view: 'ನೋಡಿ', edit: 'ಸಂಪಾದಿಸಿ', delete: 'ಅಳಿಸಿ', confirm: 'ದೃಢೀಕರಿಸಿ', close: 'ಮುಚ್ಚಿ', yes: 'ಹೌದು', no: 'ಇಲ್ಲ', welcome: 'ಸ್ವಾಗತ', location: 'ಸ್ಥಳ', latitude: 'ಅಕ್ಷಾಂಶ', longitude: 'ರೇಖಾಂಶ', yearsExp: 'ವರ್ಷಗಳ ಅನುಭವ', kmAway: 'ಕಿಮೀ ದೂರ', activeJobs: 'ಸಕ್ರಿಯ ಕೆಲಸಗಳು', noData: 'ಯಾವುದೇ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ', required: 'ಅಗತ್ಯವಿದೆ' },
  navigation: { dashboard: 'ಡ್ಯಾಶ್ಬೋರ್ಡ್', workers: 'ಕಾರ್ಮಿಕರು', bookings: 'ಬುಕ್ಕಿಂಗ್ಗಳು', profile: 'ಪ್ರೊಫೈಲ್', findService: 'ಸೇವೆ ಹುಡುಕಿ', myJobs: 'ನನ್ನ ಕೆಲಸಗಳು', adminPanel: 'ನಿರ್ವಾಹಕ ಫಲಕ', home: 'ಮುಖಪುಟ', verification: 'ಪರಿಶೀಲನೆ', workloadMonitor: 'ಕೆಲಸದ ಭಾರ ಮಾನಿಟರ್' },
  landing: { title: 'ಗಿಗ್ಸೇತು', tagline: 'ಸ್ಥಳೀಯ ಕೆಲಸ. ನ್ಯಾಯಯುತ ವಿತರಣೆ.', heroText: 'ವಿಶ್ವಾಸಾರ್ಹ ಸ್ಥಳೀಯ ವೃತ್ತಿಪರರೊಂದಿಗೆ ಸಂಪರ್ಕ ಹೊಂದಿ ಮತ್ತು ಪ್ರತಿ ಕಾರ್ಮಿಕರಿಗೆ ನ್ಯಾಯಯುತ ಅವಕಾಶಗಳನ್ನು ಸೃಷ್ಟಿಸಿ.', heroSubtext: 'ನ್ಯಾಯಯುತ ಕೆಲಸ ವಿತರಣೆಯನ್ನು ಖಚಿತಪಡಿಸುವ ಭಾರತದ ಮೊದಲ ಸಹಕಾರಿ ಸ್ವಾಮ್ಯದ ಹೈಪರ್ಲೋಕಲ್ ಗಿಗ್ ಪ್ಲಾಟ್ಫಾರ್ಮ್.', benefit1Title: 'ಪರಿಶೀಲಿಸಿದ ಕಾರ್ಮಿಕರು', benefit1Desc: 'ಪ್ರತಿ ಕಾರ್ಮಿಕರನ್ನು ಕೆಲಸ ಸ್ವೀಕರಿಸುವ ಮೊದಲು ಸಹಕಾರಿಯಿಂದ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ.', benefit2Title: 'ನ್ಯಾಯಯುತ ಕೆಲಸ ಹಂಚಿಕೆ', benefit2Desc: 'ನಮ್ಮ ನ್ಯಾಯಸಮ್ಮತ ಅಲ್ಗಾರಿದಮ್ ಎಲ್ಲಾ ಕಾರ್ಮಿಕರ ನಡುವೆ ಕೆಲಸವನ್ನು ಸಮಾನವಾಗಿ ವಿತರಿಸುತ್ತದೆ.', benefit3Title: 'ಹೈಪರ್ಲೋಕಲ್ ಸೇವೆಗಳು', benefit3Desc: 'ನಿಮ್ಮ ನೆರೆಹೊರೆಯಲ್ಲಿಯೇ ವಿಶ್ವಾಸಾರ್ಹ ವೃತ್ತಿಪರರನ್ನು ಹುಡುಕಿ.', findService: 'ಸೇವೆ ಹುಡುಕಿ', joinAsWorker: 'ಕಾರ್ಮಿಕರಾಗಿ ಸೇರಿ', builtForEveryone: 'ಎಲ್ಲರಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ', availableLanguages: 'ಇಂಗ್ಲಿಷ್, ಹಿಂದಿ ಮತ್ತು ಕನ್ನಡದಲ್ಲಿ ಲಭ್ಯ.', howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', step1: 'ಸೇವೆಯನ್ನು ಹುಡುಕಿ', step1Desc: 'ನಿಮಗೆ ಬೇಕಾದ ಸೇವೆಯ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಅವಶ್ಯಕತೆಯನ್ನು ವಿವರಿಸಿ.', step2: 'ನ್ಯಾಯಯುತ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ', step2Desc: 'ನಮ್ಮ AI-ಚಾಲಿತ ನ್ಯಾಯಸಮ್ಮತ ಅಲ್ಗಾರಿದಮ್ ಕೌಶಲ್ಯ, ದೂರ, ಲಭ್ಯತೆ ಮತ್ತು ಕೆಲಸದ ಭಾರ ಸಮತೋಲನದ ಆಧಾರದ ಮೇಲೆ ಕಾರ್ಮಿಕರನ್ನು ಶಿಫಾರಸು ಮಾಡುತ್ತದೆ.', step3: 'ಬುಕ್ ಮಾಡಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ', step3Desc: 'ಕಾರ್ಮಿಕರನ್ನು ಬುಕ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಸೇವೆಯನ್ನು ನೈಜ ಸಮಯದಲ್ಲಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.', cooperativeOwned: 'ಸಹಕಾರಿ ಸ್ವಾಮ್ಯ', cooperativeDesc: 'ಸ್ಥಳೀಯ ಸಮುದಾಯಗಳಿಂದ ಮತ್ತು ಅವರಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.', sihProject: 'ಸ್ಮಾರ್ಟ್ ಇಂಡಿಯಾ ಹ್ಯಾಕಥಾನ್ 2026 ಯೋಜನೆ' },
  auth: { loginTitle: 'ಮರಳಿ ಸ್ವಾಗತ', registerTitle: 'ಖಾತೆ ರಚಿಸಿ', selectRole: 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ', customerLogin: 'ಗ್ರಾಹಕ ಲಾಗಿನ್', workerLogin: 'ಕಾರ್ಮಿಕ ಲಾಗಿನ್', adminLogin: 'ನಿರ್ವಾಹಕ ಲಾಗಿನ್', customerRole: 'ಗ್ರಾಹಕ', workerRole: 'ಗಿಗ್ ಕಾರ್ಮಿಕ', adminRole: 'ಸಹಕಾರಿ ನಾಯಕ', noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?', haveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?', registerHere: 'ಇಲ್ಲಿ ನೋಂದಾಯಿಸಿ', loginHere: 'ಇಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ', registerAs: 'ಆಗಿ ನೋಂದಾಯಿಸಿ', customerDesc: 'ನಿಮ್ಮ ಅಗತ್ಯಗಳಿಗಾಗಿ ವಿಶ್ವಾಸಾರ್ಹ ಸ್ಥಳೀಯ ವೃತ್ತಿಪರರನ್ನು ಹುಡುಕಿ.', workerDesc: 'ಸಹಕಾರಿಯಲ್ಲಿ ಸೇರಿ ಮತ್ತು ನ್ಯಾಯಯುತ ಕೆಲಸದ ಅವಕಾಶಗಳನ್ನು ಪಡೆಯಿರಿ.', adminDesc: 'ಕಾರ್ಮಿಕರನ್ನು ನಿರ್ವಹಿಸಿ, ಪ್ರೊಫೈಲ್ಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನ್ಯಾಯಸಮ್ಮತತೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ.' },
  customer: { findService: 'ಸೇವೆ ಹುಡುಕಿ', serviceRequired: 'ಅಗತ್ಯ ಸೇವೆ', description: 'ನಿಮಗೆ ಏನು ಬೇಕು ಎಂಬುದನ್ನು ವಿವರಿಸಿ', descriptionPlaceholder: 'ಉದಾ., ಸೀಲಿಂಗ್ ಫ್ಯಾನ್ ರಿಪೇರಿ ಮಾಡಲು ಸಹಾಯ ಬೇಕು', findWorkers: 'ಕಾರ್ಮಿಕರನ್ನು ಹುಡುಕಿ', requestService: 'ಸೇವೆಯನ್ನು ವಿನಂತಿಸಿ', myBookings: 'ನನ್ನ ಬುಕ್ಕಿಂಗ್ಗಳು', currentBooking: 'ಪ್ರಸ್ತುತ ಬುಕ್ಕಿಂಗ್', bookingHistory: 'ಬುಕ್ಕಿಂಗ್ ಇತಿಹಾಸ', recommended: 'ಶಿಫಾರಸು ಮಾಡಿದ ಕಾರ್ಮಿಕರು', bestFairMatch: 'ಅತ್ಯುತ್ತಮ ನ್ಯಾಯಯುತ ಹೊಂದಾಣಿಕೆ', whyThisWorker: 'ಈ ಕಾರ್ಮಿಕ ಏಕೆ?', skillMatchReason: 'ನಿಮ್ಮ ಅವಶ್ಯಕತೆಗಳಿಗೆ ಬಲವಾದ ಕೌಶಲ್ಯ ಹೊಂದಾಣಿಕೆ', distanceReason: 'ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ಹತ್ತಿರ', availabilityReason: 'ಪ್ರಸ್ತುತ ಕೆಲಸಕ್ಕೆ ಲಭ್ಯ', workloadReason: 'ಕಡಿಮೆ ಪ್ರಸ್ತುತ ಕೆಲಸದ ಭಾರ - ನ್ಯಾಯಯುತ ವಿತರಣೆ', ratingReason: 'ಗ್ರಾಹಕಸರಿಂದ ಉನ್ನತ ರೇಟಿಂಗ್', noWorkers: 'ಈ ಸೇವೆಗೆ ಯಾವುದೇ ಕಾರ್ಮಿಕರು ಸಿಗಲಿಲ್ಲ. ಬೇರೆ ಸೇವೆ ಅಥವಾ ಸ್ಥಳವನ್ನು ಪ್ರಯತ್ನಿಸಿ.', useDefaultLocation: 'ಡೀಫಾಲ್ಟ್ ಸ್ಥಳ ಬಳಸಿ (ಬೆಂಗಳೂರು)', enterCoordinates: 'ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ನಮೂದಿಸಿ', searching: 'ಅತ್ಯುತ್ತಮ ನ್ಯಾಯಯುತ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...' , emergency: 'ತುರ್ತು ಸೇವೆ', emergencyHelp: 'ಹತ್ತಿರದ ಲಭ್ಯ ಕಾರ್ಮಿಕರಿಗೆ ಆದ್ಯತೆ ನೀಡಿ', schedule: 'ಸಮಯ ನಿಗದಿ (ಐಚ್ಛಿಕ)', useCurrentLocation: 'ಪ್ರಸ್ತುತ ಸ್ಥಳ ಬಳಸಿ', locationDenied: 'ಸ್ಥಳ ಅನುಮತಿ ದೊರೆಯಲಿಲ್ಲ', locationUnsupported: 'ಜಿಯೊಲೊಕೇಶನ್ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ', searchFailed: 'ಹುಡುಕಾಟ ವಿಫಲವಾಗಿದೆ', bookingFailed: 'ಬುಕ್ಕಿಂಗ್ ರಚಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', matches: 'ಹೊಂದಾಣಿಕೆಗಳು'},
  worker: { workerPortal: 'ಕಾರ್ಮಿಕ ಪೋರ್ಟಲ್', availability: 'ಲಭ್ಯತೆ', myJobs: 'ನನ್ನ ಕೆಲಸಗಳು', verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ', pending: 'ಪರಿಶೀಲನೆ ಬಾಕಿಯಿದೆ', rejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ', verificationStatus: 'ಪರಿಶೀಲನೆ ಸ್ಥಿತಿ', activeJobs: 'ಸಕ್ರಿಯ ಕೆಲಸಗಳು', completedJobs: 'ಪೂರ್ಣಗೊಂಡ ಕೆಲಸಗಳು', acceptJob: '✓ ಕೆಲಸ ಸ್ವೀಕರಿಸಿ', rejectJob: '✗ ಕೆಲಸ ತಿರಸ್ಕರಿಸಿ', startJob: '▶ ಕೆಲಸ ಪ್ರಾರಂಭಿಸಿ', completeJob: '✓ ಕೆಲಸ ಪೂರ್ಣಗೊಳಿಸಿ', currentWorkload: 'ಪ್ರಸ್ತುತ ಕೆಲಸದ ಭಾರ', rating: 'ರೇಟಿಂಗ್', experience: 'ಅನುಭವ', skills: 'ಕೌಶಲ್ಯಗಳು', updateProfile: 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಿ', setAvailability: 'ಲಭ್ಯತೆ ಹೊಂದಿಸಿ', available: 'ಲಭ್ಯ', partiallyAvailable: 'ಭಾಗಶಃ ಲಭ್ಯ', unavailable: 'ಲಭ್ಯವಿಲ್ಲ', service: 'ಸೇವೆ', pendingMessage: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಸಹಕಾರಿ ನಾಯಕರ ಪರಿಶೀಲನೆಗೆ ಬಾಕಿಯಿದೆ. ಪರಿಶೀಲಿಸಿದ ನಂತರ ನೀವು ಕೆಲಸಗಳನ್ನು ಸ್ವೀಕರಿಸಬಹುದು.', noJobs: 'ಪ್ರಸ್ತುತ ಯಾವುದೇ ಕೆಲಸಗಳಿಲ್ಲ. ಹೊಸ ವಿನಂತಿಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.' },
  admin: { cooperativeDashboard: 'ಸಹಕಾರಿ ಡ್ಯಾಶ್ಬೋರ್ಡ್', totalWorkers: 'ಒಟ್ಟು ಕಾರ್ಮಿಕರು', verifiedWorkers: 'ಪರಿಶೀಲಿಸಿದ ಕಾರ್ಮಿಕರು', pendingWorkers: 'ಬಾಕಿ ಕಾರ್ಮಿಕರು', customers: 'ಗ್ರಾಹಕರು', totalBookings: 'ಒಟ್ಟು ಬುಕ್ಕಿಂಗ್ಗಳು', completedJobs: 'ಪೂರ್ಣಗೊಂಡ ಕೆಲಸಗಳು', activeJobs: 'ಸಕ್ರಿಯ ಕೆಲಸಗಳು', cancelledJobs: 'ರದ್ದಾದ ಕೆಲಸಗಳು', workerVerification: 'ಕಾರ್ಮಿಕ ಪರಿಶೀಲನೆ', verifyWorker: 'ಪರಿಶೀಲಿಸಿ', rejectWorker: 'ತಿರಸ್ಕರಿಸಿ', viewProfile: 'ಪ್ರೊಫೈಲ್ ನೋಡಿ', workloadDistribution: 'ಕೆಲಸದ ಭಾರ ವಿತರಣೆ', fairnessMonitor: 'ನ್ಯಾಯಸಮ್ಮತ ಮಾನಿಟರ್', allWorkers: 'ಎಲ್ಲಾ ಕಾರ್ಮಿಕರು', pendingOnly: 'ಬಾಕಿ ಮಾತ್ರ', verifiedOnly: 'ಪರಿಶೀಲಿಸಿದ ಮಾತ್ರ', recentBookings: 'ಇತ್ತೀಚಿನ ಬುಕ್ಕಿಂಗ್ಗಳು', workerName: 'ಕಾರ್ಮಿಕರ ಹೆಸರು', serviceType: 'ಸೇವೆ ಪ್ರಕಾರ', experienceYears: 'ಅನುಭವ', status: 'ಸ್ಥಿತಿ', federationAdministration: 'ಒಕ್ಕೂಟ ಮತ್ತು ಆಡಳಿತ', cooperativeGovernance: 'ಸಹಕಾರಿ ಆಡಳಿತ', federationWorkers: 'ಒಕ್ಕೂಟದ ಕಾರ್ಮಿಕರು', admittedWorkers: 'ಅಂಗೀಕರಿಸಿದ ಕಾರ್ಮಿಕರು', pendingAdmissions: 'ಬಾಕಿ ಪ್ರವೇಶಗಳು', federationCustomers: 'ಒಕ್ಕೂಟದ ಗ್ರಾಹಕರು', welfareEligible: 'ಕಲ್ಯಾಣಕ್ಕೆ ಅರ್ಹರು', admissionGovernance: 'ಕಾರ್ಮಿಕ ಪ್ರವೇಶ ಮತ್ತು ಆಡಳಿತ', serviceCoverage: 'ಸೇವಾ ವ್ಯಾಪ್ತಿ' },
  services: { electrician: 'ಎಲೆಕ್ಟ್ರೀಶಿಯನ್', plumber: 'ಪ್ಲಂಬರ್', carpenter: 'ಮರಗೆಲಸಗಾರ', cleaner: 'ಶುಚಿಕಾರ', painter: 'ಪೇಂಟರ್', gardener: 'ತೋಟಗಾರ', applianceRepair: 'ಉಪಕರಣ ದುರಸ್ತಿ', delivery: 'ಡೆಲಿವರಿ', farmWorker: 'ಕೃಷಿ ಕಾರ್ಮಿಕ', otherServices: 'ಇತರ ಸಮುದಾಯ ಸೇವೆಗಳು' },
  fairness: { fairnessScore: 'ನ್ಯಾಯಸಮ್ಮತ ಸ್ಕೋರ್', aiMatchScore: 'AI ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್', skillMatch: 'ಕೌಶಲ್ಯ ಹೊಂದಾಣಿಕೆ', distance: 'ದೂರ', availability: 'ಲಭ್ಯತೆ', workloadBalance: 'ಕೆಲಸದ ಭಾರ ಸಮತೋಲನ', rating: 'ರೇಟಿಂಗ್', overallScore: 'ಒಟ್ಟಾರೆ ಸ್ಕೋರ್', combinedScore: 'ಸಂಯೋಜಿತ ಸ್ಕೋರ್', scoreBreakdown: 'ಸ್ಕೋರ್ ವಿವರಣೆ' },
  booking: { requested: 'ವಿನಂತಿಸಲಾಗಿದೆ', matched: 'ಹೊಂದಿಸಲಾಗಿದೆ', accepted: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ', inProgress: 'ಕೆಲಸ ಪ್ರಗತಿಯಲ್ಲಿದೆ', completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ', cancelled: 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ', newRequest: 'ಹೊಸ ವಿನಂತಿ', serviceRequest: 'ಸೇವಾ ವಿನಂತಿ', bookingDetails: 'ಬುಕ್ಕಿಂಗ್ ವಿವರಗಳು', cancelBooking: 'ಬುಕ್ಕಿಂಗ್ ರದ್ದುಮಾಡಿ', bookingCreated: 'ಬುಕ್ಕಿಂಗ್ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ!', noBookings: 'ಇನ್ನೂ ಯಾವುದೇ ಬುಕ್ಕಿಂಗ್ಗಳಿಲ್ಲ.' , customer: 'ಗ್ರಾಹಕ', worker: 'ಕಾರ್ಮಿಕ', scheduledFor: 'ನಿಗದಿತ ಸಮಯ'},
  notifications: { bookingAccepted: 'ನಿಮ್ಮ ಬುಕ್ಕಿಂಗ್ ಅನ್ನು ಸ್ವೀಕರಿಸಲಾಗಿದೆ!', bookingStarted: 'ನಿಮ್ಮ ಸೇವೆ ಈಗ ಪ್ರಗತಿಯಲ್ಲಿದೆ!', bookingCompleted: 'ನಿಮ್ಮ ಸೇವೆ ಪೂರ್ಣಗೊಂಡಿದೆ!', newBooking: 'ಹೊಸ ಸೇವಾ ವಿನಂತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ!', newBookingRequest: 'ಹೊಸ ಸೇವಾ ವಿನಂತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ!', bookingCancelled: 'ಒಂದು ಬುಕ್ಕಿಂಗ್ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ.', workerVerified: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ!', paymentReceived: 'ನಿಮ್ಮ ಪೂರ್ಣಗೊಂಡ ಸೇವೆಯ ಪಾವತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ!' },
  welfare: { title: 'ಕಾರ್ಮಿಕ ಕಲ್ಯಾಣ', insurance: 'ವಿಮೆ', fund: 'ಕಲ್ಯಾಣ ನಿಧಿ', safety: 'ಸುರಕ್ಷತಾ ತರಬೇತಿ', certifications: 'ಪ್ರಮಾಣಪತ್ರಗಳು', none: 'ಯಾವುದೇ ಪ್ರಮಾಣಪತ್ರಗಳಿಲ್ಲ' },
  payment: { title: 'ಡಿಜಿಟಲ್ ಪಾವತಿ', amount: 'ಸೇವಾ ಮೊತ್ತ (₹)', payNow: 'ಈಗ ಪಾವತಿಸಿ', paid: 'ಪಾವತಿ ಪೂರ್ಣಗೊಂಡಿದೆ', success: 'ಡೆಮೊ ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ', failed: 'ಪಾವತಿ ವಿಫಲವಾಗಿದೆ', validAmount: 'ಮಾನ್ಯ ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ' },
  rating: { title: 'ಈ ಸೇವೆಗೆ ರೇಟಿಂಗ್ ನೀಡಿ', feedback: 'ನಿಮ್ಮ ಅನುಭವವನ್ನು ತಿಳಿಸಿ (ಐಚ್ಛಿಕ)', submit: 'ರೇಟಿಂಗ್ ಸಲ್ಲಿಸಿ', thanks: 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು!', failed: 'ರೇಟಿಂಗ್ ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ' },
  invoice: { view: 'ಇನ್‌ವಾಯ್ಸ್ ನೋಡಿ', failed: 'ಇನ್‌ವಾಯ್ಸ್ ರಚಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ' },
  forecast: { title: 'AI ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ', synthetic: 'ಪ್ರೋಟೋಟೈಪ್ ಮುನ್ಸೂಚನೆ ಸಿಂಥೆಟಿಕ್ ಡೆಮೊ ಡೇಟಾವನ್ನು ಬಳಸುತ್ತದೆ. ಉತ್ಪಾದನೆಯಲ್ಲಿ ನೈಜ ಬುಕ್ಕಿಂಗ್ ಡೇಟಾ ಬಳಸಿ.' }
};
